name: Build, Tag e Push da imagem para repositório ECR
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    uses: "EzzioMoreira/cicd_centralizado/.github/workflows/build_push_image_ecr.yaml@feat/add-actions-ecr"
    with:
      ECR_REPOSITORY: "metalcorp"
      TAG_IMAGE: "latest"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
