name: "Terraform Valida Modulo"

on:
  pull_request:

jobs:
  terraform:
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@v1"
    with: 
      os_version: "self-hosted"
    secrets:
      token: ${{ secrets.TOKEN }}