name: "Terraform Valida Modulo"

on:
  push:
  pull_request:

jobs:
  terraform:
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@v1"
    with: 
      os_version: "ubuntu-20.04"
      secrets:
        token: ${{ secrets.TOKEN }}