name: CI Metal Corp

on:
  push:
    branches:
      - "main"
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.16', '1.16' ]
    name: Go ${{ matrix.go }} teste execução
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go run hello.go
        
      - name: Notifica time Discord
        uses: th0th/notify-discord@v0.4.1
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_DISCORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "build"
          GITHUB_JOB_STATUS: ${{ job.status }}
