name: CI Metal Corp

on:
  push:
    branches:
      - "main"
  #workflow_dispatch:
    
jobs:
  teste:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.15', '1.16', '1.17' ]
    name: Go ${{ matrix.go }} teste execução
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go run hello.go
