name: CI Metal Corp

on:
  push:
    branches:
      - "main"
    
jobs:
  teste:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.16', '1.17' ]
    name: Go ${{ matrix.go }} teste execução
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go run hello.go
  
  build:
    runs-on: ubuntu-latest
    needs: [teste]
    steps:
      - uses: actions/checkout@v3
      - name: Docker setup
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        id: login-docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image Docker
        env:
          DOCKER_REGISTRY: ${{ steps.login-docker.outputs.registry }}
          DOCKER_REPOSITORY: appmetalcorp
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$(echo ${GITHUB_SHA} | cut -c1-8) .
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$(echo ${GITHUB_SHA} | cut -c1-8)
  
  notifica:
    runs-on: ubuntu-latest
    needs: [teste, build]
    steps:
      - name: Notifica time Discord
        uses: th0th/notify-discord@v0.4.1
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_DISCORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Pipeline aplicação Metal Corp"
          GITHUB_JOB_STATUS: ${{ job.status }}
